INSERT INTO "Category" ("id", "name", "name_en", "description", "description_en") VALUES
(1, '动植物及检疫物（470号公告）', 'Animals, Plants, and Quarantine Objects (Announcement No. 470)', '中华人民共和国禁止携带、寄递进境的动植物及其产品和其他检疫物名录。', 'List of animals, plants, products, and other quarantine objects prohibited from being carried or posted into the People''s Republic of China.'),
(2, '禁止进境物品', 'Generally Prohibited Imports', '根据中华人民共和国海关法规定，禁止进境的物品。', 'Items prohibited from import according to the Customs Law of the People''s Republic of China.'),
(3, '限制进境物品', 'Generally Restricted Imports', '根据中华人民共和国海关法规定，限制进境的物品。', 'Items restricted from import according to the Customs Law of the People''s Republic of China.');

INSERT INTO "Item" ("name", "name_en", "description", "description_en", "status", "restrictions", "restrictions_en", "category_id", "source", "last_updated") VALUES
('活动物', 'Live Animals', '包括所有的哺乳动物、鸟类、鱼类、甲壳类、两栖类、爬行类、昆虫类和其他无脊椎动物，动物遗传物质。', 'Including all mammals, birds, fish, crustaceans, amphibians, reptiles, insects, and other invertebrates, and animal genetic material.', 'Prohibited', '犬、猫除外', 'Except for dogs and cats', 1, '470号公告', NULL),
('（生或熟）肉类及其制品', '(Raw or Cooked) Meat and Products', '含脏器类。', 'Including offal/organs.', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('水生动物产品', 'Aquatic Animal Products', '无', 'None', 'Prohibited', '干制、熟制、发酵后制成的食用酱汁水生动物产品除外。', 'Except for aquatic animal products processed into edible sauces (dried, cooked, or fermented).', 1, '470号公告', NULL),
('动物源性乳及乳制品', 'Animal-derived Milk and Dairy Products', '包括生乳、巴氏杀菌乳、灭菌乳、调制乳、发酵乳，奶油、黄油奶酪、炼乳等乳制品。', 'Including raw milk, pasteurized milk, sterilized milk, formulated milk, fermented milk, cream, butter, cheese, condensed milk, and other dairy products.', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('蛋及其制品', 'Eggs and Egg Products', '包括鲜蛋皮蛋、咸蛋、蛋液、蛋壳、蛋黄酱等蛋源产品。', 'Including fresh eggs, preserved eggs, salted eggs, liquid egg, eggshells, mayonnaise, and other egg source products.', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('燕窝', 'Edible Bird''s Nests', '无', 'None', 'Prohibited', '经商业无菌处理的罐头装燕窝除外。', 'Except for canned edible bird''s nests that have undergone commercial sterilization.', 1, '470号公告', NULL),
('油脂类、皮张、毛类、蹄（爪）骨、牙、角类及其制品', 'Fats, Hides, Hair, Hoof/Claw/Bone, Teeth, Horns and their Products', '无', 'None', 'Prohibited', '经加工处理且无血污、肌肉和脂肪等的蛋壳类、蹄（爪）骨角类、甲壳类等工艺品除外。', 'Except for handicrafts made from eggshells, hooves, claws, bones, horns, crustaceans, etc., that have been processed and are free of blood stains, muscle, and fat.', 1, '470号公告', NULL),
('动物源性饲料、中药材、肥料', 'Animal-derived Feed, Chinese Herbal Medicine, and Fertilizer', '动物源性。', 'Animal-derived.', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('新鲜水果、蔬菜', 'Fresh Fruits and Vegetables', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('鲜切花', 'Fresh Cut Flowers', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('烟叶', 'Tobacco Leaves', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('种子、种苗及其他具有繁殖能力的植物、植物产品及材料', 'Seeds, Seedlings, and other Propagative Plants, Plant Products, and Materials', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('动植物病原体、害虫及其他有害生物', 'Animal/Plant Pathogens, Pests, and other Harmful Organisms', '菌种、病毒、寄生虫等。', 'Including bacterial strains, viruses, parasites, etc.', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('兽用生物制品', 'Veterinary Biological Products', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('细胞、器官组织、血液及其制品等生物材料及其他高风险生物因子', 'Cells, Organ Tissues, Blood and their Products, and other High-Risk Biological Factors', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('动物尸体、动物标本、动物源性废弃物', 'Animal Carcasses, Animal Specimens, Animal-derived Waste', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('土壤及有机栽培介质', 'Soil and Organic Cultivation Media', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('转基因生物材料', 'Genetically Modified Biological Materials', '无', 'None', 'Prohibited', '无', 'None', 1, '470号公告', NULL),
('武器、仿真武器、弹药及爆炸物品', 'Weapons, Counterfeit Weapons, Ammunition, and Explosives', '各种。', 'Various types.', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('伪造的货币及伪造的有价证券', 'Counterfeit Currencies and Forged Securities', '无', 'None', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('对中国政治、经济、文化、道德有害的物品', 'Items Detrimental to China''s Politics, Economy, Culture, or Morality', '印刷品、胶卷、照片、唱片、影片、录音带、录像带、激光视盘、计算机存储介质及其它物品。', 'Printed matter, films, photos, records, movies, audiotapes, videotapes, laser discs, computer storage media, and other items.', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('各种烈性毒药', 'Various Potent Poisons', '无', 'None', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('麻醉品、精神药物', 'Narcotics and Psychotropic Substances', '鸦片、吗啡、海洛英、大麻以及其它能使人成瘾的。', 'Opium, morphine, heroin, cannabis, and other addictive substances.', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('带有危险性病菌、害虫及其它有害生物的动植物及其产品', 'Animals/Plants and Products with Dangerous Pathogens, Pests, or other Harmful Organisms', '无', 'None', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('有碍人畜健康的、来自疫区的以及其它能传播疾病的食品、药品或其它物品', 'Food, Medicine, or other Items Detrimental to Human/Animal Health, from Epidemic Areas, or that can Spread Disease', '无', 'None', 'Prohibited', '无', 'None', 2, '进境物品', NULL),
('无线电收发信机、通信保密机', 'Radio Transceivers and Confidential Communication Devices', '无', 'None', 'Restricted', '无', 'None', 3, '限制进境', NULL),
('烟、酒', 'Tobacco and Alcohol', '无', 'None', 'Restricted', '无', 'None', 3, '限制进境', NULL),
('濒危的和珍贵的动物、植物及其种子和繁殖材料', 'Endangered and Precious Animals, Plants, Seeds, and Propagative Material', '均含标本。', 'Specimens are included.', 'Restricted', '无', 'None', 3, '限制进境', NULL),
('国家货币', 'National Currency', '无', 'None', 'Restricted', '无', 'None', 3, '限制进境', NULL),
('海关限制进境的其它物品', 'Other Items Restricted by Customs', '无', 'None', 'Restricted', '无', 'None', 3, '限制进境', NULL);
